local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("Premium Binbinvoroblox11 Gui", "Ocean")
local Tab = Window:NewTab("Main block fruits")
local Section = Tab:NewSection("Main block fruits")
Section:NewButton("PremiumV1", "PremiumV1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/BlockfruitskeysystemautochestV1.lua",true))()
end)
Section:NewButton("PremiumV2", "PremiumV2", function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/BlockfruitskeysystemautochestV2.lua",true))()
end)
Section:NewButton("MUKURO HUB", "MUKURO HUB V1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/MUKUROHUB_V1_KEY_SETAM_GUi_MUKUROHUB.lua"))()
end)
Section:NewButton("PADO HUB", "PADO HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/REWzaKunGz1/premium/main/PadoHub'))()
end)
Section:NewButton("KING HUB", "KING HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KINGHUB01/KING-HUB-NO-1/main/kingshubno1"))()
end)
Section:NewButton("MANGO HUB", "MANGO HUB", function()
    loadstring(game:HttpGet("https://gitlab.com/L1ZOT/mango-hub/-/raw/main/Mango-Bloxf-Fruits-Beta"))()
end)
Section:NewButton("TABLE HUB", "TABLE HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/AltsegoD/scripts/egoD/tablekhoc.lua"))()
end)
Section:NewButton("THUNDER Z HUB", "THUNDER Z HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Mobile-Loader"))()
end)
Section:NewButton("BONK HUB", "BONK HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Toonza555/BONKHUBV2/main/Loader"))()
end)
Section:NewButton("Crimson HUB", "Crimson HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/TirSANX/CrimsonHUB/main/C_Loader'))()
end)
Section:NewButton("CFRAME HUB V2", "CFRAME HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CFrame3310/CFrameHub/main/BloxFruitV2.lua"))()
end)
Section:NewButton("PLAYBACK X HUB", "PLAYBACK X HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/NeaPchX2/Playback-X-HUB/main/PlaybackXHub.lua"))()
end)
Section:NewButton("CFRAME HUB V1", "CFRAME HUB V1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CFrame3310/CFrameHub/main/BloxFruit_Mobile.lua"))()
end)
Section:NewButton("SPEED HUB", "SPEED HUB", function()
    (getgenv()).Key = "SPEED-JMSG-8ABT-DHNV-E9EE"
(getgenv()).DiscordId = "866309890301100083"
loadstring(game:HttpGet("https://raw.githubusercontent.com/NeaPchX2/SpeedHub44/main/SpeedHub.lua"))()
end)
Section:NewButton("MUKURO V2", "MUKURO V2", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
Section:NewButton("ZAQUE HUB PC", "ZAQUE HUB PC", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/ZaqueHub/BloxFruitPC/main/Protected.lua'))()
end)
Section:NewButton("ZAQUEHUB Mobile", "ZAQUEHUB Mobile", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Mei2232/ZaqueHub/main/Zaque%20Hub"))()
end)
Section:NewButton("HOHO HUB", "HOHO HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI'))()
end)
Section:NewButton("Void HUB NEW", "Void HUB NEW", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Efe0626/VoidHub/main/Script"))()
end)
Section:NewButton("URANIUM  HUB NEW", "URANIUM  HUB NEW", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Augustzyzx/UraniumMobile/main/NewVersion.lua"))()
end)
Section:NewButton("BLACK TRAP HUB NEW", "BLACK TRAP HUB NEW", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/S4nZz/bt_project/main/Games/BlacktrapScript.txt'))()
end)
Section:NewButton("Ripper Hub ", "Ripper Hub ", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
Section:NewButton("NEVA HUB", "NEVA HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/VEZ2/NEVAHUB/main/2'))()
end)
Section:NewButton("Hydro menu hub", "Hydro menu hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FRX397/Hydrohub/main/Hydro_hub",true))()
end)
Section:NewButton("ATR HUB", "ATR HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/scriptpastebin/raw/main/ATR",true))()
end)
Section:NewButton("ZEN GAME HUB", "ZEN GAME HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Kaizenofficiall/KaiZen/main/GameHub", true))()
end)
Section:NewButton("Under Hub v1", "Under Hub v1", function()
    (getgenv()).Key = "UNDER-HUB-BETA" --ห้ามลบ
loadstring(game:HttpGet("https://raw.githubusercontent.com/xSxyz/keyunderhub/main/Loading_Ui"))()
end)
Section:NewButton("Under Hub V2 l New", "Under Hub V2 l New", function()
    getgenv().JoinTeam = "Pirate" -- / Marine
shared.keys = "6a3918e1b0350f925d3fe91493499d9" --Key
loadstring(game:HttpGet("https://raw.githubusercontent.com/xSxyz/Project-Dev-beta/main/Project-005-V2"))()
end)
local Tab = Window:NewTab("FarmFactoryTycoon")
local Section = Tab:NewSection("FarmFactoryTycoon")
Section:NewButton("Infiniyr Money", "Infiniyr Money", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/CreatorProfessional/fft/main/generateinfinitemoney'))()
end)
local Tab = Window:NewTab("king legacy")
local Section = Tab:NewSection("king legacy")
Section:NewButton("Hoho Hub", "HoHo HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI'))()
end)
Section:NewButton("One X Hub", "One X Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/xOne2/King-Legacy/main/README.md"))()
end)
local Tab = Window:NewTab("pet simulator x")
local Section = Tab:NewSection("pet simulator x")
Section:NewButton("CLOUD HUB GUI", "CLOUD HUB GUI", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/BadScripters/CloudHub/main/hub"))()
end)
Section:NewButton("Nike Fucker V4.9", "Nike Fucker V4.9", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RobloxMguiSetup/Trade-scam-more/main/dupe%2B%20dupe%20gems", true))()
end)
Section:NewButton("BLACK TRAP HUB NEW", "BLACK TRAP HUB NEW", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/S4nZz/bt_project/main/Games/BlacktrapScript.txt'))()
end)
Section:NewButton("Project-WD Hub", "Project-WD Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Main.lua"))()
end)
Section:NewButton("jmes Hub", "jmes Hub", function()
    loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/jmesfo0/RobloxScripts/main/psx-jmes.lua"))()
end)
Section:NewButton("auto farm+ anti ban", "auto farm+ anti ban", function()
    _G.Stop = false -- false = script is on; true = script is off
_G.World = "Fantasy" -- Worlds: "Fantasy" & "Spawn"
_G.Area = "Enchanted Forest" -- See the above comment and select something..
 
loadstring(game:HttpGet('https://pastebin.com/raw/tGUJRjqb'))()
end)
Section:NewButton("no name ", "no name", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/SHAREHACK/script/main/psx'))()
end)
Section:NewButton("boy Hub", "boy Hub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Solx69/Shit-Boy-Hub-Main/main/Pet%20Sim%20X'))()
end)
