local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("Premium Binbinvoroblox11 Gui", "Ocean")
local Tab = Window:NewTab("Main")
local Section = Tab:NewSection("Main")
Section:NewButton("Infiniyr Money", "Infiniyr Money", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/CreatorProfessional/fft/main/generateinfinitemoney'))()
end)
local Tab = Window:NewTab("Credits")
local Section = Tab:NewSection("Credits")
local Tab2 = window:NewTab("Credits")
local Tab2Section = Tab2:NewSection("block fruits ")
local Tab2Section = Tab2:NewSection("block fruits")
local Tab2 = window:NewTab("Credits")
local Tab2Section = Tab2:NewSection("farm factory tycoon")
local Tab2Section = Tab2:NewSection("farm factory tycoon")
end)
Section:NewButton("Main Block Fruits", "Main Block Fruits", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/Blockfruits.lua',true))()
end)
