local Library = loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/Orion/Kaizenofficiall/Binbinvogaming/source.lua'))()
local Window = Library.CreateLib("Premium Binbinvoroblox11 Gui", "Ocean")
local Tab = Window:NewTab("king legacy")
local Section = Tab:NewSection("king legacy")
Section:NewButton("Hoho Hub", "HoHo HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI'))()
end)
Section:NewButton("One X Hub", "One X Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/xOne2/King-Legacy/main/README.md"))()
end)
Section:NewButton("MuKuro Hub ", "MuKuro Hub", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
