local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("binbinvo Hub v1", "Ocean")
local Tab = Window:NewTab("Main")
local Section = Tab:NewSection("Main")
Section:NewButton("Skeleton Key [Execute In The Shop]", "Gives Skeleton Key", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/YSj8WCwS"))() 
end)
Section:NewButton("Crucifix", "Blocks Entity Attacks.", function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/Doors_Crucifix_binbinvogaming.lua",true))()
end)
Section:NewButton("Spawn Rush", "Spawns Rush", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUsercodeblockfuits/DeletedUserCode/main/spawn_rush.lua",true))()
end)
Section:NewButton("Spawn Ambush", "Spawns Ambush", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/spawn_ambush.lua",true))()   
end)
