local Library = loadstring(game:HttpGet("https://pastebin.com/raw/vff1bQ9F"))()
local Window = Library.CreateLib("BinbinvoGaming HUB", "Ocean")
local Tab = Window:NewTab("block fruits")
local Section = Tab:NewSection("block fruits")
Section:NewButton("BinbinvoGaming Hub NEW", "BinbinvoGaming Hub NEW", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/BinbinvoGaming/DeletedUserCode/main/BF/BinbinvoGamingHub.lua'))()
end)
Section:NewButton("Hit Bot", "HIT BOT", function()
   loadstring(game:HttpGet('https://pastebin.com/raw/ghZNXvsh'))()
end)
Section:NewButton("infiniteyield Hub", "infiniteyield Hub", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()
end)
Section:NewButton("HOHO HUB PREMIUM", "HOHO HUB PREMIUM", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/Kaizenofficiall/BinbinvoGaming/HoHohubPremium.lua'))()
end)
Section:NewButton("ALONE HUB l AUTO BOUNTY l New", "ALONE HUB l AUTO BOUNTY l New", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/Kaizenofficiall/BinbinvoGaming/AloneHub/autoframbounty.lua'))()
end)
Section:NewButton("URANIUM  HUB NEW", "URANIUM  HUB NEW", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Augustzyzx/UraniumMobile/main/UraniumKak.lua"))()
end)
Section:NewButton("Zee Hub NEW", "URANIUM  HUB NEW", function()
    loadstring(game:HttpGet("https://scriptdee.com/free/ZeeHubNew.lua"))()
end)
Section:NewButton("Deity_Hub", "Deity_Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Larinax999/leak/main/Deity_Hub_NextGen.lua"))()
end)
Section:NewButton("MADOX HUB", "MADOX HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Fiend1sh/FiendMain/main/MadoxHubKey", true))()
end)
Section:NewButton("Synapse X mobile", "Synapse X mobile", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/tWGxhNq0"))()
end)
Section:NewButton("BLxze Hub", "BLxze Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/WindowsXp12/BlxzeRBLX/main/BLxzeHub.lua"))()
end)
Section:NewButton("BLCK HUB", "BLCK HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Superikka/Main/main/BLCKHUBKEY",true))()
end)
Section:NewButton("XETER HUB", "XETER HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/XETERHUB.lua'))()
end)
Section:NewButton("PremiumV1", "PremiumV1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/BlockfruitskeysystemautochestV1.lua",true))()
end)
Section:NewButton("PremiumV2", "PremiumV2", function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/BlockfruitskeysystemautochestV2.lua",true))()
end)
Section:NewButton("ChiBa Hub", "ChiBa Hub", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/KindIhave/ChibaHuB/main/Chiba-BF.txt'))()
end)
Section:NewButton("ICE HUB", "ICE HUB", function()
   loadstring(game:HttpGet('https://icehub.cf/IceHubLoader'))()
end)
Section:NewButton("Lazer Hub", "Lazer Hub", function()
   loadstring(game:HttpGet("https://raw.githubusercontent.com/Lazerxl/overlazerxkaito-nahee/main/README.md"))()
end)
Section:NewButton("Winnable Hub V2", "Winnable Hub V2", function()
    _G.Mode = "NextWorld" -- Normal / NextWorld / Aimbot
loadstring(game:HttpGet("https://raw.githubusercontent.com/xlostpexz/winnablehubfullhd/Fps/Loading.lua"))()
end)
Section:NewButton("Winnable Hub V1", "Winnable Hub V1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/xlostpexz/tyuiop/Fps/Loading.lua"))()
end)
Section:NewButton("Rein Hub", "Rein Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Kaizenofficiall/KaiZen/main/Rein", true))()
end)
Section:NewButton("MUKURO HUB", "MUKURO HUB V1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/MUKUROHUB_V1_KEY_SETAM_GUi_MUKUROHUB.lua"))()
end)
Section:NewButton("PADO HUB", "PADO HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/REWzaKunGz1/premium/main/PadoHub'))()
end)
Section:NewButton("KING HUB", "KING HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KINGHUB01/KING-HUB-NO-1/main/kingshubno1"))()
end)
Section:NewButton("MANGO HUB", "MANGO HUB", function()
    loadstring(game:HttpGet("https://gitlab.com/L1ZOT/mango-hub/-/raw/main/Mango-Bloxf-Fruits-Beta"))()
end)
Section:NewButton("TABLE HUB", "TABLE HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/AltsegoD/scripts/egoD/tablekhoc.lua"))()
end)
Section:NewButton("THUNDER Z HUB", "THUNDER Z HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ThunderZ-05/HUB/main/Mobile-Loader"))()
end)
Section:NewButton("BONK HUB", "BONK HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Toonza555/BONKHUBV2/main/Loader"))()
end)
Section:NewButton("Crimson HUB", "Crimson HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/TirSANX/CrimsonHUB/main/C_Loader'))()
end)
Section:NewButton("CFRAME HUB V2", "CFRAME HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CFrame3310/CFrameHub/main/BloxFruitV2.lua"))()
end)
Section:NewButton("PLAYBACK X HUB l New", "PLAYBACK X HUB l New", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/NeaPchX2/Playback-X-HUB/main/Playback%20X%20Hub%20Service%20X%20V2.lua"))()
end)
Section:NewButton("CFRAME HUB V1", "CFRAME HUB V1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CFrame3310/CFrameHub/main/BloxFruit_Mobile.lua"))()
end)
Section:NewButton("SPEED HUB", "SPEED HUB", function()
    (getgenv()).Key = "SPEED-JMSG-8ABT-DHNV-E9EE"
(getgenv()).DiscordId = "866309890301100083"
loadstring(game:HttpGet("https://raw.githubusercontent.com/NeaPchX2/SpeedHub44/main/SpeedHub.lua"))()
end)
Section:NewButton("MUKURO V2", "MUKURO V2", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
Section:NewButton("ZAQUE HUB PC", "ZAQUE HUB PC", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/ZaqueHub/BloxFruitPC/main/Protected.lua'))()
end)
Section:NewButton("ZAQUEHUB Mobile", "ZAQUEHUB Mobile", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Mei2232/ZaqueHub/main/Zaque%20Hub"))()
end)
Section:NewButton("HOHO HUB", "HOHO HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/acsu123/HOHO_H/main/Loading_UI'))()
end)
Section:NewButton("Void HUB NEW", "Void HUB NEW", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Efe0626/VoidHub/main/Script"))()
end)
Section:NewButton("BLACK TRAP HUB NEW", "BLACK TRAP HUB NEW", function()
    loadstring(game:HttpGetAsync("https://gitlab.com/Sky2836/test/-/raw/main/Script_All_In-One"))()
end)
Section:NewButton("Ripper Hub ", "Ripper Hub ", function()
    loadstring(game:HttpGet"https://raw.githubusercontent.com/xQuartyx/DonateMe/main/ScriptLoader")()
end)
Section:NewButton("NEVA HUB", "NEVA HUB", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/VEZ2/NEVAHUB/main/2'))()
end)
Section:NewButton("Hydro menu hub", "Hydro menu hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/FRX397/Hydrohub/main/Hydro_hub",true))()
end)
Section:NewButton("ATR HUB", "ATR HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/scriptpastebin/raw/main/ATR",true))()
end)
Section:NewButton("ZEN GAME HUB", "ZEN GAME HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Kaizenofficiall/KaiZen/main/GameHub", true))()
end)
Section:NewButton("Under Hub v1", "Under Hub v1", function()
    (getgenv()).Key = "UNDER-HUB-BETA" --ห้ามลบ
loadstring(game:HttpGet("https://raw.githubusercontent.com/xSxyz/keyunderhub/main/Loading_Ui"))()
end)
Section:NewButton("Under Hub V2 l New", "Under Hub V2 l New", function()
    getgenv().JoinTeam = "Pirate" -- / Marine
shared.keys = "6a3918e1b0350f925d3fe91493499d9" --Key
loadstring(game:HttpGet("https://raw.githubusercontent.com/xSxyz/Project-Dev-beta/main/Project-005-V2"))()
end)
Section:NewButton("B_Genesis Hub", "B_Genesis Hub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/raw-scriptpastebin/raw/main/B_Genesis'))()
end)
Section:NewButton("String Hub v2", "String Hub V2", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/StringV2/StringHub/main/BF.lua", true))()
end)
Section:NewButton("TNG HUB", "TNG HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/tngaming123/TNGHub/main/TNG%20Hub%20V3.lua"))()
end)
Section:NewButton("ONE X HUB", "ONE X HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/xOne2/One-x-HUB/main/README.md"))()
end)
Section:NewButton("MODZ BACK HUB", "MODZ BACK HUB", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/natoppo044/GGEZ/main/MODZ_HUB.txt", true))()
end)
Section:NewButton("ZAMA HUB V2", "ZAMA HUB V2", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RimuruScripter/Zama-Hub/main/LoadingScriptV2"))()
end)
Section:NewButton("Switch Hub", "Switch Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/LoserEiEi/EieiName/main/CrackSwitchHub"))();
-- Switch Hub crack old update version --
end)
Section:NewButton("ShowItem", "ShowItem", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CFA-HUB/CFAHub-Free/main/ShowItem.lua"))()
end)
local Tab = Window:NewTab("pet simulator x")
local Section = Tab:NewSection("pet simulator x")
Section:NewButton("CLOUD HUB GUI", "CLOUD HUB GUI", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/BadScripters/CloudHub/main/hub"))()
end)
Section:NewButton("Nike Fucker V4.9", "Nike Fucker V4.9", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RobloxMguiSetup/Trade-scam-more/main/dupe%2B%20dupe%20gems", true))()
end)
Section:NewButton("BLACK TRAP HUB NEW", "BLACK TRAP HUB NEW", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/S4nZz/bt_project/main/Games/BlacktrapScript.txt'))()
end)
Section:NewButton("Project-WD Hub", "Project-WD Hub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Muhammad6196/Project-WD/main/Main.lua"))()
end)
Section:NewButton("jmes Hub", "jmes Hub", function()
    loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/jmesfo0/RobloxScripts/main/psx-jmes.lua"))()
end)
Section:NewButton("no name ", "no name", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/SHAREHACK/script/main/psx'))()
end)
Section:NewButton("boy Hub", "boy Hub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Solx69/Shit-Boy-Hub-Main/main/Pet%20Sim%20X'))()
end)
local Tab = Window:NewTab("Misc")
local Section = Tab:NewSection("Misc")
Section:NewButton("COPY DISCORD", "COPY DISCORD", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/Copy/Discord.lua'))()
end)
Section:NewButton("COPY YOUTUBE", "COPY YOUTUBE", function()
   loadstring(game:HttpGet('https://raw.githubusercontent.com/DeletedUserCodeblockfuits/DeletedUserCode/main/copy/Youtube.lua'))()
end)
